CREATE TABLE `students`(
    `no` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    `name` VARCHAR(255) NOT NULL COMMENT '姓名',
    `sid` VARCHAR(255) NOT NULL COMMENT '學號',
    `email` VARCHAR(255) NOT NULL COMMENT 'email'
);
CREATE TABLE `Scores`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `aubject` VARCHAR(255) NOT NULL,
    `score` INT NOT NULL,
    `fk_sid` VARCHAR(255) NOT NULL
);